name = "dhanu"
type = "javascript"
account_id = "c41777a685e3ad00430d4babfa2aa548"
workers_dev = true
compatibility_date = "2024-06-16"

[build]
command = "npm run build"
[build.upload]
format = "modules"
main = "./dist/index.js"
pages_build_output_dir = "build"
